[phases.setup]
nixPkgs = ["php", "php81Packages.composer", "nodejs", "mysql"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan route:clear",
  "php artisan migrate --force"
]

[phases.start]
cmds = [
    "php-fpm -D",   # Avvia PHP-FPM in background
  "nginx -g 'daemon off;'"  # Avvia Nginx
]
